name: my_project
services:
  web:
    image: nginx:alpine
    ports:
      - 8081:80
  db: 
    image: postgres:alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
  